"""Add source_family

Revision ID: 29f770e2a655
Revises: 5f8728dc89ee
Create Date: 2026-04-13 10:58:22.533881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f770e2a655'
down_revision: Union[str, None] = '5f8728dc89ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('source_family', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'source_family')
    # ### end Alembic commands ###
