"""add_chunk_position_sub

Revision ID: 5f8728dc89ee
Revises: f3a2c1d89e45
Create Date: 2026-03-27 15:39:37.009604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8728dc89ee'
down_revision: Union[str, None] = 'f3a2c1d89e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_position_sub', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_position_sub')
    # ### end Alembic commands ###
