"""Add category model

Revision ID: 8067abc29b2c
Revises: b7f81510702a
Create Date: 2026-03-23 19:53:56.247957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8067abc29b2c'
down_revision: Union[str, None] = 'b7f81510702a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('conversations', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
